version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-apppick-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: apppick
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  spring-boot-app:
    image: 2024-msg-server:1.1
    container_name: spring-boot-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dbname
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password