version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-apppick-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: apppick
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  spring-boot-server:
    image: apppick-server:latest
    container_name: apppick-server
    ports:
      - "8081:8081"  # 호스트의 8081 -> 컨테이너 8081
    depends_on:
      - mysql
    environment:
      # Spring Boot 내부에서 8081 포트로 구동되도록 설정 (application.properties 참고)
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/apppick
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password