[project]
name = "apppick"
version = "0.1.0"
description = ""
authors = [
    {name = "mic050r", email = "s2216@e-mirim.hs.kr"}
]
requires-python = ">=3.9"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.110.0"
uvicorn = "^0.29.0"
sqlalchemy = "^2.0.0"
pydantic = "^2.0.0"
passlib = { version = "^1.7", extras = ["bcrypt"] }
python-dotenv = "^1.0"
httpx = "^0.28"
beautifulsoup4 = "^4.13"
requests = "^2.32"
langchain-core = "^0.1.27"
langchain-openai = "^0.0.8"
starlette = "^0.36.3"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
